### ISSUE TITLE
No battery icon

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#1] opened 2022-11-28 13:41 UTC
In edit mode I see this:

![image](https://user-images.githubusercontent.com/3447868/204291732-fc89abad-6b0c-4815-b933-cf4333bec50e.png)

but in normal view, only the long bar is visible, no icon. 

![image](https://user-images.githubusercontent.com/3447868/204291978-b0dfe727-052a-4d22-aa36-0c9f59b8a690.png)

Plasma 5.25.5, Kubuntu 22.10

**Comment by lonelytransistor** [comment] 2022-11-28 14:17
Well that was intended. The idea was to have an applet which is invisible and impossible to click on except for the bar to create a seamless integration into the panel's background itself. I wanted to basically create a background for a panel which changes depending on the battery state.
Because of the "impossible to click on" part I added a placeholder icon when in edit mode, so the user can still move the applet and change its settings.

May I ask why do you want an icon to be visible all the time? Also, what do you want it to do or show?

**Comment by cipricus** [comment] 2022-11-28 15:45
I understand about the icon. 

I am on a laptop and I want to see the percentage in numbers and to have an area to click on / scroll for brightness etc. But your tool can be used in combination with other widgets. 

![image](https://user-images.githubusercontent.com/3447868/204320431-25773690-9cf5-4c3d-bcde-8fcd801cd015.png)

**Comment by lonelytransistor** [comment] 2022-11-28 15:58
I mean I can add it if you think its useful. Good suggestion, let's leave it as a TODO.

**Comment by cipricus** [comment] 2022-11-28 16:20
> I mean I can add it if you think its useful. Good suggestion, let's leave it as a TODO.

In order to avoid posting a new request: you might consider a way to show visually that the battery is charging or discharging - either with the future battery icon, or with some change in the bars.

The thin bar should show the "the battery percentage that will be used during the next hour (by default) at current power draw". What does it show when the battery is charging and no battery percentage is "used"?

**Comment by lonelytransistor** [comment] 2022-11-28 16:52
> In order to avoid posting a new request: you might consider a way to show visually that the battery is charging or discharging - either with the future battery icon, or with some change in the bars.

Noted and added.
> The thin bar should show the "the battery percentage that will be used during the next hour (by default) at current power draw". What does it show when the battery is charging and no battery percentage is "used"?

It shows the charging rate. I.e. what amount of battery will be charged within the hour.

**Comment by lonelytransistor** [comment] 2022-11-30 15:42
I'm closing this issue as will not fix, because there are other plasmoids on the KDE store which fill this role.

**Closed as not planned by lonelytransistor** 2022-11-30 15:42 UTC

**Comment by cipricus** [comment] 2022-12-05 08:51
> It shows the charging rate. I.e. what amount of battery will be charged within the hour.

That should be added in the description of the auxiliary bar, here: https://github.com/lonelytransistor/kde_batterybar#usage

Also, in rate bar settings, "discharge" is the only term used to discuss color and opacity. "Charge/discharge" should be used instead.
